### ISSUE TITLE
API backend: API not available from browser

### ISSUE THREAD

**Issue by mickahell** [IceKhan13/purplecaffeine#41]
### Steps to reproduce the problem
It seems, we can't access the data of the API from the browser.

<img width="511" alt="Capture d’écran 2023-05-18 à 13 20 08" src="https://github.com/IceKhan13/purplecaffeine/assets/20951376/73e1d51e-a4c3-44ba-8c8f-d19420c895b6">

**Comment by mickahell** [comment]
Information from DEBUG mode :
<img width="1076" alt="Capture d’écran 2023-05-18 à 13 57 53" src="https://github.com/IceKhan13/purplecaffeine/assets/20951376/4b078315-3fea-4f76-be76-16e36d76d709">

**Comment by AnsahMohammad** [comment]
I'm receiving this when attempting to access through a browser. It occurs because the API requires authentication using an Access Key token. However, should I add a view with an authentication **textbox** so that users can access it through a browser?

![image](https://github.com/IceKhan13/purplecaffeine/assets/85027826/e4cd0ddd-e138-4707-b08b-3f544c3c9a42)

**Comment by mickahell** [comment]
Perfect like that :D

Don't integrate authentication box, plugin for setting up token exist

**Comment by mickahell** [comment]
Indeed, I run it just now and got the same.
<img width="594" alt="Capture d’écran 2023-05-27 à 18 36 37" src="https://github.com/IceKhan13/purplecaffeine/assets/20951376/f9aa8657-1c03-48ff-853b-8ce96e5ee92c">

Now I don't have the CSS but i think that's because of Docker 🤔

**Comment by mickahell** [comment]
Ok I found why :)

Close this issue in #61
