### ISSUE TITLE
Widget: high-level design

### ISSUE THREAD

**Issue by IceKhan13** [IceKhan13/purplecaffeine#6]
We need high level design on widget. 
It can be simple sketch on a piece of paper, but we need all know how it will be looking like at the end.

Epic https://github.com/IceKhan13/purplecaffeine/issues/3

**Comment by mentesniker** [comment]
@IceKhan13 what features do you think we can include in the widget?
Statistics?
a table with previous results?

**Comment by mentesniker** [comment]
After some consideration based on my personal experience, I would like to have a widget like this: 
![purple coffe drawio](https://user-images.githubusercontent.com/35209340/234878574-2d552fb8-e2c8-48f8-af9b-ad22eb91e026.png)
After you click on a trial button you will be able to see the bar plot.
The measurements and the parameters are hidden by default since you don't care about them about 99% of the time. they are going to be shown only when you click on their respective buttons.
The search can be done by tags and by name. The modify button can edit the tags and the name.
A small variation could be that instead of show params and show measurements, you could download this info to a .txt file if you click on the buttons.

**Comment by mentesniker** [comment]
@IceKhan13 can we add tags, and name to the things which are going to be saved to the database?

**Comment by mentesniker** [comment]
This is the draw.io file of the design, feel free to make modifications:
[purple coffe.zip](https://github.com/IceKhan13/purplecaffeine/files/11360207/purple.coffe.zip)

**Comment by IceKhan13** [comment]
Thank you!

**Comment by IceKhan13** [comment]
Playing around with layouts

![purple coffe-v2 drawio](https://user-images.githubusercontent.com/8796709/235362061-95215eb2-cf9a-4197-ba8c-901a326e0e04.png)

----

Attaching file too

[purple coffe widget layout.zip](https://github.com/IceKhan13/purplecaffeine/files/11361653/purple.coffe.widget.layout.zip)

**Comment by IceKhan13** [comment]
Closing this and moving to wiki https://github.com/IceKhan13/purplecaffeine/wiki#widget-design-proposal
